In [1]:
from array import *
array_num = array('i', [1, 3, 5, 3, 7, 1, 9, 3])
print("Original array: "+str(array_num))
num_list = array_num.tolist()
print("Convert the said array to an ordinary list with the same items:")
print(num_list)

Original array: array('i', [1, 3, 5, 3, 7, 1, 9, 3])
Convert the said array to an ordinary list with the same items:
[1, 3, 5, 3, 7, 1, 9, 3]


In [2]:
import numpy as np
m = np.arange(6).reshape(2,3)
print("Original matrix:")
print(m)
result =  np.trace(m)
print("Condition number of the said matrix:")
print(result)

Original matrix:
[[0 1 2]
 [3 4 5]]
Condition number of the said matrix:
4


In [13]:
import numpy as np
x = np.array([[0, 10, 20], [20, 30, 40]])
print("Original array: ")
print(x)
print("Values bigger than 10 =", x[x>10])
print("Their indices are ", np.nonzero(x > 10))


Original array: 
[[ 0 10 20]
 [20 30 40]]
Values bigger than 10 = [20 20 30 40]
Their indices are  (array([0, 1, 1, 1], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [23]:
 arr1 = array([1, 2, 3, 4, 5 ])
arr2 = array([6, 7, 8, 9, 10, 11, 12])
arr3 = ([])

if len(arr1) == len(arr2):  # Finding minimum length array
    minLength = len(arr1)
    pass
elif len(arr1) > len(arr2):
    minLength = len(arr2)
    arr3 = arr1.copy()     # Copy max array into new array
else:
    minLength = len(arr1)
    arr3 = arr2.copy()     # Copy max array into new array

for i in range(minLength):
    arr3[i] = arr1[i] + arr2[i]  # adding array and replacing in new array

print(arr3)

[ 7  9 11 13 15 11 12]


In [15]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[0.40044696 0.11490408 0.65289395 0.06163587 0.33162013 0.66327413
  0.71110792 0.15870555 0.75211184 0.13249927]
 [0.94967069 0.1463248  0.25936808 0.36440845 0.95514434 0.82169667
  0.62212706 0.86887105 0.11874023 0.42895954]
 [0.79494377 0.93269056 0.59890178 0.53847922 0.18189166 0.87234814
  0.98598878 0.55721761 0.26702485 0.26638582]
 [0.8022849  0.84110161 0.90260415 0.205358   0.95751924 0.09120004
  0.40463502 0.15271687 0.94011221 0.91017322]
 [0.0585607  0.19015753 0.59485998 0.08033077 0.22061976 0.85380896
  0.78476825 0.85051044 0.49607401 0.48370124]]

Subtract the mean of each row of the said matrix:

[[ 0.00252699 -0.28301589  0.25497398 -0.3362841  -0.06629984  0.26535416
   0.31318796 -0.23921442  0.35419187 -0.2654207 ]
 [ 0.3961396  -0.40720629 -0.29416301 -0.18912264  0.40161325  0.26816558
   0.06859597  0.31533996 -0.43479086 -0.12457155]
 [ 0.19535655  0.33310334 -0.00068544 -0.061108   -0.41769556  0.27276092
   0.38640156 -0.04236961 -0.3